/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as interfaces from "./interfaces";
export { ERC165__factory } from "./ERC165__factory";
export { ERC4973__factory } from "./ERC4973__factory";
export { ERC4973Permit__factory } from "./ERC4973Permit__factory";
