/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { ERC165 } from "./ERC165";
export type { ERC4973 } from "./ERC4973";
export type { ERC4973Permit } from "./ERC4973Permit";
