/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as badgesTSol from "./Badges.t.sol";
export type { badgesTSol };
export type { Badges } from "./Badges";
