/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IERC165 } from "./IERC165";
export type { IERC4973 } from "./IERC4973";
export type { IERC4973Permit } from "./IERC4973Permit";
export type { IERC721Metadata } from "./IERC721Metadata";
