/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IERC4973Permit,
  IERC4973PermitInterface,
} from "../../../../../lib/ERC4973/src/interfaces/IERC4973Permit";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        internalType: "string",
        name: "uri",
        type: "string",
      },
      {
        internalType: "bytes",
        name: "signature",
        type: "bytes",
      },
    ],
    name: "mintWithPermission",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IERC4973Permit__factory {
  static readonly abi = _abi;
  static createInterface(): IERC4973PermitInterface {
    return new utils.Interface(_abi) as IERC4973PermitInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IERC4973Permit {
    return new Contract(address, _abi, signerOrProvider) as IERC4973Permit;
  }
}
