/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc4973 from "./ERC4973";
export type { erc4973 };
import type * as openzeppelinContracts from "./openzeppelin-contracts";
export type { openzeppelinContracts };
