on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  deploy_to_mainnets_on_merge:
    env:
      DEPLOYER_PRIVATE_KEY: ${{ secrets.DEPLOYER_PRIVATE_KEY }}
      OPTIMISM_RPC_URL: ${{ secrets.OPTIMISM_RPC_URL }}
      OPTIMISTIC_ETHERSCAN_API_KEY: ${{ secrets.OPTIMISTIC_ETHERSCAN_API_KEY }}
      ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
      DEFENDER_TEAM_API_KEY: ${{ secrets.DEFENDER_TEAM_API_KEY }}
      DEFENDER_TEAM_API_SECRET_KEY: ${{ secrets.DEFENDER_TEAM_API_SECRET_KEY }}
      OPTIMISM_BADGES_ADDRESS: ${{ secrets.OPTIMISM_BADGES_ADDRESS }}
      OPTIMISM_RAFT_ADDRESS: ${{ secrets.OPTIMISM_RAFT_ADDRESS }}
      OPTIMISM_SPECDATAHOLDER_ADDRESS: ${{ secrets.OPTIMISM_SPECDATAHOLDER_ADDRESS }}
      OPTIMISM_GNOSIS_SAFE: ${{ secrets.OPTIMISM_GNOSIS_SAFE }}
      MAINNET_GNOSIS_SAFE: ${{ secrets.MAINNET_GNOSIS_SAFE }}
      MAINNET_RPC_URL: ${{ secrets.MAINNET_RPC_URL }}
      MAINNET_BADGES_ADDRESS: ${{ secrets.MAINNET_BADGES_ADDRESS }}
      MAINNET_RAFT_ADDRESS: ${{ secrets.MAINNET_RAFT_ADDRESS }}
      MAINNET_SPECDATAHOLDER_ADDRESS: ${{ secrets.MAINNET_SPECDATAHOLDER_ADDRESS }}
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          submodules: recursive
          node-version: 16
          cache: yarn

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install submodules
        run: git submodule update --init

      - name: Install yarn dependencies
        run: yarn

      - name: Run forge install
        run: forge install

      - name: Deploy
        run: |
          set -e

          function get_code_at_ref() {
            git show "$1":src/Badges.sol
            git show "$1":src/Raft.sol
            git show "$1":src/SpecDataHolder.sol
          }

          function switch_branch() {
            local branch_name="$1"
            local ref="$2"
            git switch -c "$branch_name" "$ref" || git switch "$branch_name"
          }

          function create_proposal() {
            local implementation="$1"
            local name="$2"

            node scripts/createProposal.js "$implementation" 'badges' "$name" || {
              echo "Failed to create a proposal for the new Badges implementation on $name"
              exit 1
            }
          }

          last_tag=$(git describe --tags --abbrev=0)
          git_branch=$last_tag
          switch_branch "$git_branch" "$last_tag"

          badges_code_at_last_tag=$(cat src/Badges.sol)
          raft_code_at_last_tag=$(cat src/Raft.sol)
          sdh_code_at_last_tag=$(cat src/SpecDataHolder.sol)

          git switch main

          current_badges_code=$(cat src/Badges.sol)
          current_raft_code=$(cat src/Raft.sol)
          current_sdh_code=$(cat src/SpecDataHolder.sol)

          declare -A networks=(
              ["optimism"]="$OPTIMISM_RPC_URL $OPTIMISTIC_ETHERSCAN_API_KEY"
              ["mainnet"]="$MAINNET_RPC_URL $ETHERSCAN_API_KEY"              
          )

          for networkName in "${!networks[@]}"; do
              read rpc_url etherscan_api_key <<<"${networks[$networkName]}"
              if [ "$badges_code_at_last_tag" != "$current_badges_code" ]; then
                  echo "CODE CHANGED ON BADGES CONTRACT. THIS IS A TEST, SO YOU MUST MANUALLY DEPLOY USING ./scripts/deploy_and_verify_implementation"

                  # badgesImplementation=$(forge create src/Badges.sol:Badges --private-key "$DEPLOYER_PRIVATE_KEY" --verify --rpc-url "$rpc_url" --etherscan-api-key "$etherscan_api_key" | grep "Deployed to:" | cut -d " " -f 3) || {
                  #     echo "Failed to deploy the new Badges implementation on $networkName"
                  #     exit 1
                  # }

                  # node scripts/createProposal.js "$badgesImplementation" 'badges' "$networkName" || {
                  #     echo "Failed to create a proposal for the new Badges implementation on $networkName"
                  #     exit 1
                  # }
              fi

              if [ "$raft_code_at_last_tag" != "$current_raft_code" ]; then
                  echo "CODE CHANGED ON RAFT CONTRACT. THIS IS A TEST, SO YOU MUST MANUALLY DEPLOY USING ./scripts/deploy_and_verify_implementation"
                  # raftImplementation=$(forge create src/Raft.sol:Raft --private-key "$DEPLOYER_PRIVATE_KEY" --verify --rpc-url "$rpc_url" --etherscan-api-key "$etherscan_api_key" | grep "Deployed to:" | cut -d " " -f 3) || {
                  #     echo "Failed to deploy the new Raft implementation on $networkName"
                  #     exit 1
                  # }
                  # node scripts/createProposal.js "$raftImplementation" 'raft' "$networkName" || {
                  #     echo "Failed to create a proposal for the new Raft implementation on $networkName"
                  #     exit 1
                  # }
              fi

              if [ "$sdh_code_at_last_tag" != "$current_sdh_code" ]; then
                  echo "CODE CHANGED ON SDH CONTRACT. THIS IS A TEST, SO YOU MUST MANUALLY DEPLOY USING ./scripts/deploy_and_verify_implementation"

                  # sdhImplementation=$(forge create src/SpecDataHolder.sol:SpecDataHolder --private-key "$DEPLOYER_PRIVATE_KEY" --verify --rpc-url "$rpc_url" --etherscan-api-key "$etherscan_api_key" | grep "Deployed to:" | cut -d " " -f 3) || {
                  #     echo "Failed to deploy the new SpecDataHolder implementation on $networkName"
                  #     exit 1
                  # }
                  # node scripts/createProposal.js "$sdhImplementation" 'specDataHolder' "$networkName" || {
                  #     echo "Failed to create a proposal for the new SpecDataHolder implementation on $networkName"
                  #     exit 1
                  # }
              fi

              echo "All implementations deployed successfully on $networkName"
          done
