on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  deploy_to_mainnets_on_merge:
    env:
      DEPLOYER_PRIVATE_KEY: ${{ secrets.DEPLOYER_PRIVATE_KEY }}
      OPTIMISM_RPC_URL: ${{ secrets.OPTIMISM_RPC_URL }}
      OPTIMISTIC_ETHERSCAN_API_KEY: ${{ secrets.OPTIMISTIC_ETHERSCAN_API_KEY }}
      ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
      DEFENDER_TEAM_API_KEY: ${{ secrets.DEFENDER_TEAM_API_KEY }}
      DEFENDER_TEAM_API_SECRET_KEY: ${{ secrets.DEFENDER_TEAM_API_SECRET_KEY }}
      OPTIMISM_BADGES_ADDRESS: ${{ secrets.OPTIMISM_BADGES_ADDRESS }}
      OPTIMISM_RAFT_ADDRESS: ${{ secrets.OPTIMISM_RAFT_ADDRESS }}
      OPTIMISM_SPECDATAHOLDER_ADDRESS: ${{ secrets.OPTIMISM_SPECDATAHOLDER_ADDRESS }}
      OPTIMISM_GNOSIS_SAFE: ${{ secrets.OPTIMISM_GNOSIS_SAFE }}
      MAINNET_GNOSIS_SAFE: ${{ secrets.MAINNET_GNOSIS_SAFE }}
      MAINNET_RPC_URL: ${{ secrets.MAINNET_RPC_URL }}
      MAINNET_BADGES_ADDRESS: ${{ secrets.MAINNET_BADGES_ADDRESS }}
      MAINNET_RAFT_ADDRESS: ${{ secrets.MAINNET_RAFT_ADDRESS }}
      MAINNET_SPECDATAHOLDER_ADDRESS: ${{ secrets.MAINNET_SPECDATAHOLDER_ADDRESS }}
      POLYGON_RPC_URL: ${{ secrets.POLYGON_RPC_URL }}
      POLYGON_BADGES_ADDRESS: ${{ secrets.POLYGON_BADGES_ADDRESS }}
      POLYGON_RAFT_ADDRESS: ${{ secrets.POLYGON_RAFT_ADDRESS }}
      POLYGON_SPECDATAHOLDER_ADDRESS: ${{ secrets.POLYGON_SPECDATAHOLDER_ADDRESS }}
      POLYGON_ETHERSCAN_API_KEY: ${{ secrets.POLYGON_ETHERSCAN_API_KEY }}
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          submodules: recursive
          node-version: 16
          cache: yarn

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install submodules
        run: git submodule update --init

      - name: Install yarn dependencies
        run: yarn

      - name: Run forge install
        run: forge install

      - name: Deploy
        run: |
           set -e

           prev_tag=$(git describe --tags --abbrev=0)

           echo "PREVIOUS TAG = $prev_tag"
           git branch prev_tag $prev_tag
           git switch prev_tag

           badges_code_at_prev_tag=$(cat src/Badges.sol)
           raft_code_at_prev_tag=$(cat src/Raft.sol)
           sdh_code_at_prev_tag=$(cat src/SpecDataHolder.sol)

           git switch dev

           latest_badges_code=$(cat src/Badges.sol)
           latest_raft_code=$(cat src/Raft.sol)
           latest_sdh_code=$(cat src/SpecDataHolder.sol)

           declare -A networks=(
              ["optimism"]="$OPTIMISM_RPC_URL $OPTIMISTIC_ETHERSCAN_API_KEY"
              ["polygon"]="$POLYGON_RPC_URL $POLYGON_ETHERSCAN_API_KEY"
           )

           for networkName in "${!networks[@]}"; do
               read rpc_url etherscan_api_key <<<"${networks[$networkName]}"

               # Initialize the list of successfully deployed contracts
               deployedContracts=()

               if [ "$badges_code_at_prev_tag" != "$latest_badges_code" ]; then
                   implementationAddress=$(forge create src/Badges.sol:Badges --private-key "$DEPLOYER_PRIVATE_KEY" --verify --rpc-url "$rpc_url" --etherscan-api-key "$etherscan_api_key" | grep "Deployed to:" | cut -d " " -f 3) || {
                       echo "Failed to deploy the new Badges implementation on $networkName"
                       exit 1
                   }
                   echo "Badges contract deployed. implementationAddress: $implementationAddress"
                   node scripts/createProposal.js "$implementationAddress" 'badges' "$networkName" || {
                       echo "Failed to create a proposal for the new Badges implementation on $networkName"
                       exit 1
                   }
                   # Add the contract name to the deployedContracts list
                   deployedContracts+=("Badges")
               fi

               if [ "$raft_code_at_prev_tag" != "$latest_raft_code" ]; then
                   implementationAddress=$(forge create src/Raft.sol:Raft --private-key "$DEPLOYER_PRIVATE_KEY" --verify --rpc-url "$rpc_url" --etherscan-api-key "$etherscan_api_key" | grep "Deployed to:" | cut -d " " -f 3) || {
                       echo "Failed to deploy the new Raft implementation on $networkName"
                       exit 1
                   }
                   echo "Raft contract deployed. implementationAddress: $implementationAddress"
                   node scripts/createProposal.js "$implementationAddress" 'raft' "$networkName" || {
                       echo "Failed to create a proposal for the new Raft implementation on $networkName"
                       exit 1
                   }
                   # Add the contract name to the deployedContracts list
                   deployedContracts+=("Raft")
               fi

               if [ "$sdh_code_at_prev_tag" != "$latest_sdh_code" ]; then
                   implementationAddress=$(forge create src/SpecDataHolder.sol:SpecDataHolder --private-key "$DEPLOYER_PRIVATE_KEY" --verify --rpc-url "$rpc_url" --etherscan-api-key "$etherscan_api_key" | grep "Deployed to:" | cut -d " " -f 3) || {
                       echo "Failed to deploy the new SpecDataHolder implementation on $networkName"
                       exit 1
                   }
                   echo "SDH contract deployed. implementationAddress: $implementationAddress"
                   node scripts/createProposal.js "$implementationAddress" 'specDataHolder' "$networkName" || {
                       echo "Failed to create a proposal for the new SpecDataHolder implementation on $networkName"
                       exit 1
                   }
                   # Add the contract name to the deployedContracts list
                   deployedContracts+=("SpecDataHolder")
               fi

               # Check the deployment at the end of the loop
               if [ ${#deployedContracts[@]} -gt 0 ]; then
                   echo "Successfully deployed: ${#deployedContracts[@]} contract(s) (${deployedContracts[*]}) on $networkName"
               else
                   echo "No implementations deployed on $networkName"
               fi
           done
