on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  if_merged:
    env:
      DEPLOYER_PRIVATE_KEY: ${{ secrets.DEPLOYER_PRIVATE_KEY }}
      OPTIMISM_RPC_URL: ${{ secrets.OPTIMISM_RPC_URL }}
      OPTIMISTIC_ETHERSCAN_API_KEY: ${{ secrets.OPTIMISTIC_ETHERSCAN_API_KEY }}
      OPTIMISM_BADGES_ADDRESS: ${{ secrets.OPTIMISM_BADGES_ADDRESS }}
      OPTIMISM_RAFT_ADDRESS: ${{ secrets.OPTIMISM_RAFT_ADDRESS }}
      OPTIMISM_SPECDATAHOLDER_ADDRESS: ${{ secrets.OPTIMISM_SPECDATAHOLDER_ADDRESS }}
      OPTIMISM_GNOSIS_SAFE: ${{ secrets.OPTIMISM_GNOSIS_SAFE }}
      DEFENDER_TEAM_API_KEY: ${{ secrets.DEFENDER_TEAM_API_KEY }}
      DEFENDER_TEAM_API_SECRET_KEY: ${{ secrets.DEFENDER_TEAM_API_SECRET_KEY }}
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          submodules: recursive
          node-version: ${{ matrix.node }}
          cache: yarn

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install submodules
        run: git submodule update --init

      - name: Install yarn dependencies
        run: yarn

      - name: Run forge install
        run: forge install

      - run: |
          # Get the latest tag
          last_tag=$(git describe --tags --abbrev=0)

          # Create new branch from that tag
          git branch last_tag_branch $last_tag

          #switch to it
          git switch last_tag_branch

          # Get the contents of src/Badges.sol from the latest tag
          last_tag_badges=$(cat src/Badges.sol)
          last_tag_raft=$(cat src/Raft.sol)
          last_tag_sdh=$(cat src/SpecDataHolder.sol)

          # Checkout the current commit
          git switch main

          # Get the contents of src/Badges.sol from the current commit
          current_badges=$(cat src/Badges.sol)
          current_raft=$(cat src/Raft.sol)
          current_sdh=$(cat src/SpecDataHolder.sol)

          # Compare the contents of src/Badges.sol between the latest tag and the current commit
          if [ "$last_tag_badges" != "$current_badges" ]; then
            # if the code of the Badges contract has changed since the time we tagged the repo, we should deploy a new implementation

            ## deploy and verify 
            # note: here we're getting the output of forge create and grabbing the address
            badgesImplementation=$(forge create src/Badges.sol:Badges --private-key $DEPLOYER_PRIVATE_KEY --verify --rpc-url $OPTIMISM_RPC_URL --etherscan-api-key $OPTIMISTIC_ETHERSCAN_API_KEY | grep "Deployed to:" | cut -d " " -f 3)

            # run our js file that creates the proposal
            echo "badgesImplementation = $badgesImplementation"
            node scripts/createProposal.js $badgesImplementation 'badges' 'optimism'
            echo "BADGES: deployed implementation, verified, proposed"
          else
            echo "no changes in Badges between this commit and the last tagged version"
          fi

          if [ "$last_tag_raft" != "$current_raft" ]; then
            # if the code of the Raft contract has changed since the time we tagged the repo, we should deploy a new implementation          
            
            ## deploy and verify 
            # note: here we're getting the output of forge create and grabbing the address
            raftImplementation=$(forge create src/Raft.sol:Raft --private-key $DEPLOYER_PRIVATE_KEY --verify --rpc-url $OPTIMISM_RPC_URL --etherscan-api-key $OPTIMISTIC_ETHERSCAN_API_KEY | grep "Deployed to:" | cut -d " " -f 3)

            # run our js file that creates the proposal
            node scripts/createProposal.js $raftImplementation 'raft' 'optimism'
            echo "RAFT: deployed implementation, verified, proposed"
          else
            echo "no changes in Raft between this commit and the last tagged version"            
          fi

          if [ "$last_tag_sdh" != "$current_sdh" ]; then
            # if the code of the SpecDataHolder contract has changed since the time we tagged the repo, we should deploy a new implementation

            ## deploy and verify 
            # note: here we're getting the output of forge create and grabbing the address
            sdhImplementation=$(forge create src/SpecDataHolder.sol:SpecDataHolder --private-key $DEPLOYER_PRIVATE_KEY --verify --rpc-url $OPTIMISM_RPC_URL --etherscan-api-key $OPTIMISTIC_ETHERSCAN_API_KEY | grep "Deployed to:" | cut -d " " -f 3)

            # run our js file that creates the proposal
            node scripts/createProposal.js $sdhImplementation 'specDataHolder' 'optimism'
            echo "SpecDataHolder: deployed implementation, verified, proposed"
          else
            echo "no changes in SpecDataHolder between this commit and the last tagged version"            
          fi
      - run: |
          # Tag the current commit with the version specified in package.json
          version=$(grep '"version":' package.json | cut -d'"' -f4)
          git tag $version
          git push origin $version
